# -*- coding: utf-8 -*-
"""Generador_contrasena.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1py5GB2VCItlfTmQerxPZoLJdJZPfeRnA

primero importamos radom para asegurarnos que las contraseñas cumplan con la funcion de ser aleatorias
"""

import random
import string

"""Funcion para generar contraseñas

condicionales
"""

def generar_contrasena(longitud, mayusculas, numeros, simbolos):
  caracteres = string.ascii_lowercase

  if mayusculas:
    caracteres += string.ascii_uppercase

  if numeros:
    caracteres += string.digits

  if simbolos:
    caracteres += string.punctuation

  contrasena = ""

  for i in range(longitud):
    contrasena += random.choice(caracteres)

  return contrasena

"""Evaluar fortaleza de la contraseña"""

def evaluar_fortaleza(contrasena):

  longitud =len(contrasena)

  tiene_mayusculas = any(c.isupper() for c in contrasena)
  tiene_numeros = any(c.isdigit()for c in contrasena)
  tiene_simbolos = any(c in string.punctuation for c in contrasena)

  puntuacion = 0

  if longitud >= 8:
    puntuacion += 1

  if longitud >= 10:
    puntuacion += 1

  if tiene_mayusculas:
    puntuacion += 1

  if tiene_numeros:
    puntuacion += 1

  if tiene_simbolos:
    puntuacion +=1

  if puntuacion <= 2:
    return "Debil"

  elif puntuacion <= 4:
    return "Media"

  else:
    return "Fuerte"

"""prueba 1"""

print(generar_contrasena(12,True,True,True))

"""Programa principal

Paso 1: Pedir longitud y validar si es menor a 8

aqui se añadio una advertencia en caso de que la contraseña tengs menos de 8 caracteres. Esto con la finalidad garantizar la efectividad del sistema
"""

while True:

    longitud = int(input("Ingrese la longitud de la contraseña: "))

    if longitud >= 8:
        break

    print("Advertencia: la contraseña será débil.")

    continuar = input("¿Desea continuar con esta longitud? (s/n): ")

    if continuar.lower() == "s":
        break

    print("Por favor ingrese una nueva longitud.")

"""Paso 2: pedir las preferencias"""

mayusculas = input("Incluir mayúsculas? (si/no):").lower() == "si"

numeros = input("Incluir numeros?(si/no):").lower() == "si"

simbolos = input("Incluir simbolos? (si/no):").lower() == "si"

"""Paso 3: Generar contraseña"""

contrasena = generar_contrasena(
    longitud,
    mayusculas,
    numeros,
    simbolos
)

"""paso 4: Mostrar contraseñas"""

print("\nContraseña generada:")
print(contrasena)

"""Paso 5: evaluar fortaleza"""

fortaleza = evaluar_fortaleza(contrasena)
print("\nFortaleza:")
print(fortaleza)

"""Paso 6: Guarda contraseña"""

guardar = input("\n¿Desea guardar la contraseña? (si/no): ")

"""Paso 7: Crear archivo TXT"""

if guardar.lower() == "si":
  archivo = open("contrasena_guardada", "w")

  archivo.write(contrasena)

  archivo.close()

  print("Contraseña guardada correctamente en contrasenas_guardadas")

else:
  print("La contraseña no fue guardada")

"""prueba 2"""

print(contrasena)

"""Paso 8: Evaluar fortaleza"""

fortaleza = evaluar_fortaleza(contrasena)
print("\nFortaleza de la contraseña:", fortaleza)

print(generar_contrasena(12, True, True, True))
print(generar_contrasena(12, True, True, True))
print(generar_contrasena(12, True, True, True))

"""Se ejecuto una pruba de tres contraseñas con la misma longitus para asegurar que el comando random.choice(caracteres) estuviera funcionando correctaamente

"""

print(contrasena)
print(fortaleza)